spring.application.name=spring-learn1
logging.level.com.springframework=INFO
logging.level.com.cognizant1.spring_learn1=DEBUG
logging.pattern.console=%d{yyMMdd}|%d{HH:mm:ss.SSS}|%-20.20thread|%5p|%-25.25logger{25}|%25M|%m%n

